# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb81e064fc22e1f9844bc905c94e6c8e45f23e8292813d8dd4ca0ee110be99c9877fd30e2faf501f656b229fa4f5e2b0c0a7609e8793737582e26af129e5f85d

test:
  secret_key_base: 88f17aea0e6dbc9aa7eb59e4f791f471caba9f36f628c46462395ddd815001a2665ad2796fa2b192458853960185e37efc6e4f29a82dbc63fc37e28166ecc92f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
